services:
  ml_project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ardenpalme
      secrets:
        - github_token
    ports:
      - "8888:8888"
    volumes:
      - .:/home/ML_project
    working_dir: /home/ML_project
    tty: true

secrets:
  github_token:
    file: .github_token
